name: host-HAMR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: install_deps
        run: |
          export DEBIAN_FRONTEND="noninteractive"
          export TZ="America/Los_Angeles"
          sudo apt-get update -qq
          sudo apt-get install -qq -y git-core gcc g++ cmake automake m4 wget swig python-dev
          python3 -mvenv py3k_testing
          source py3k_testing/bin/activate
          python3 -mpip install numpy

      # build for host only
      - name: build_host
        run: |
          source py3k_testing/bin/activate
          mkdir build_host
          cd build_host
          cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON -DHAMR_ENABLE_PYTHON=ON -DCMAKE_INSTALL_PREFIX=`pwd`/../../hamr-install ..
          make -j2 install
          cd ..

      # test the host build
      - name: test_host
        run: |
          source py3k_testing/bin/activate
          cd build_host
          tmp_llp=$LD_LIBRARY_PATH
          tmp_pp=$PYTHONPATH
          source ./bin/hamr_python_env.sh
          ctest --output-on-failure
          export LD_LIBRARY_PATH=$tmp_llp PYTHONPATH=$tmp_pp
          cd ..
