# This is a basic workflow to help you get started with Actions

name: hamr_ci

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install_deps
        run: |
          export DEBIAN_FRONTEND="noninteractive"
          export TZ="America/Los_Angeles"
          sudo apt-get update -qq
          sudo apt-get install -qq -y git-core gcc g++ gfortran cmake subversion automake m4 wget swig python-dev
          python3 -mvenv py3k_testing
          source py3k_testing/bin/activate
          python3 -mpip install numpy
          deactivate

      # Runs a set of commands using the runners shell
      - name: build
        run: |
          source py3k_testing/bin/activate
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON -DHAMR_ENABLE_PYTHON=ON -DCMAKE_INSTALL_PREFIX=`pwd`/../../hamr-install ..
          make -j2
          export LD_LIBRARY_PATH=`pwd`/lib:$LD_LIBRARY_PATH
          export PYTHONPATH=`pwd`/lib:$PYTHONPATH
          ctest --output-on-failure
          make -j2 install
